<?php

namespace Database\Seeders;

use App\Models\MenuCategory;
use App\Models\MenuItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $menu = [
            [
                'name'           => 'Coffee & Lattes',
                'name_es'        => 'Café y Lattes',
                'description'    => '12 oz · 2 shots of espresso · whole milk · Oat milk +$1 · 16 oz upgrade +$1',
                'description_es' => '12 oz · 2 shots de espresso · leche entera · Leche de avena +$1 · 16 oz +$1',
                'sort_order'  => 1,
                'items'       => [
                    [
                        'name'           => 'Blueberry Latte',
                        'name_es'        => 'Latte de Arándano',
                        'price'          => 6.50,
                        'description'    => 'House blueberry sauce layered with espresso and whole milk — a signature favourite.',
                        'description_es' => 'Salsa de arándano de la casa con espresso y leche entera — un favorito de la casa.',
                        'featured'       => true,
                        'sort'           => 1,
                    ],
                    [
                        'name'           => 'Brown Sugar Shaken Espresso',
                        'name_es'        => 'Espresso Agitado con Azúcar Morena',
                        'price'          => 6.50,
                        'description'    => 'Espresso shaken over brown sugar and ice, topped with vanilla cold foam and a dash of cinnamon.',
                        'description_es' => 'Espresso agitado con azúcar morena y hielo, coronado con espuma fría de vainilla y un toque de canela.',
                        'featured'       => true,
                        'sort'           => 2,
                    ],
                    [
                        'name'           => 'Mazapán Latte',
                        'name_es'        => 'Latte de Mazapán',
                        'price'          => 6.50,
                        'description'    => 'Inspired by the classic Mexican candy — mazapán powder dissolved in espresso with caramel syrup and steamed milk.',
                        'description_es' => 'Inspirado en el clásico dulce mexicano — mazapán disuelto en espresso con jarabe de caramelo y leche al vapor.',
                        'featured'       => true,
                        'sort'           => 3,
                    ],
                    [
                        'name'           => 'Nutella Latte',
                        'name_es'        => 'Latte de Nutella',
                        'price'          => 6.00,
                        'description'    => 'Nutella drizzled around the cup with hazelnut syrup, espresso, and steamed whole milk.',
                        'description_es' => 'Nutella esparcida alrededor del vaso con jarabe de avellana, espresso y leche entera al vapor.',
                        'featured'       => false,
                        'sort'           => 4,
                    ],
                    [
                        'name'           => 'Spanish Latte',
                        'name_es'        => 'Latte Español',
                        'price'          => 6.00,
                        'description'    => 'Sweetened condensed milk, espresso, and steamed milk with a touch of cinnamon. Creamy and indulgent.',
                        'description_es' => 'Leche condensada, espresso y leche al vapor con un toque de canela. Cremoso e indulgente.',
                        'featured'       => false,
                        'sort'           => 5,
                    ],
                    [
                        'name'           => 'Cookies & Creme Latte',
                        'name_es'        => 'Latte de Galletas y Crema',
                        'price'          => 6.00,
                        'description'    => 'Chocolate drizzle, crumbled cookies, vanilla syrup, and whipping cream — dessert in a cup.',
                        'description_es' => 'Chocolate, galletas trituradas, jarabe de vainilla y crema batida — un postre en taza.',
                        'featured'       => false,
                        'sort'           => 6,
                    ],
                    [
                        'name'           => 'French Toast Latte',
                        'name_es'        => 'Latte de Tostada Francesa',
                        'price'          => 6.00,
                        'description'    => 'Maple syrup and brown sugar with espresso and steamed milk, finished with a cinnamon-sugar sprinkle.',
                        'description_es' => 'Jarabe de maple y azúcar morena con espresso y leche al vapor, con un toque de canela y azúcar.',
                        'featured'       => false,
                        'sort'           => 7,
                    ],
                    [
                        'name'           => 'Dulce de Leche Latte',
                        'name_es'        => 'Latte de Dulce de Leche',
                        'price'          => 6.00,
                        'description'    => 'Dulce de leche drizzled around the cup with vanilla syrup, espresso, and steamed milk, topped with cinnamon and nutmeg.',
                        'description_es' => 'Dulce de leche esparcido alrededor del vaso con jarabe de vainilla, espresso y leche al vapor, con canela y nuez moscada.',
                        'featured'       => false,
                        'sort'           => 8,
                    ],
                    [
                        'name'           => 'Caramel Macchiato',
                        'name_es'        => 'Macchiato de Caramelo',
                        'price'          => 6.00,
                        'description'    => 'Caramel-drizzled cup, caramel syrup, and steamed milk topped with espresso and a golden caramel drizzle.',
                        'description_es' => 'Vaso bañado en caramelo, jarabe de caramelo y leche al vapor coronado con espresso y un toque dorado de caramelo.',
                        'featured'       => false,
                        'sort'           => 9,
                    ],
                    [
                        'name'           => 'Mexican Coffee "Café de Olla"',
                        'name_es'        => 'Café de Olla',
                        'price'          => 6.00,
                        'description'    => 'Traditional cinnamon and piloncillo notes brewed into a warm, spiced espresso drink.',
                        'description_es' => 'Notas tradicionales de canela y piloncillo en una bebida caliente y especiada de espresso.',
                        'featured'       => false,
                        'sort'           => 10,
                    ],
                    [
                        'name'           => 'Chocolate Abuelita Latte',
                        'name_es'        => 'Latte de Chocolate Abuelita',
                        'price'          => 6.00,
                        'description'    => 'Abuelita chocolate powder with a pinch of salt, dash of cinnamon, espresso, and steamed milk.',
                        'description_es' => 'Chocolate Abuelita en polvo con una pizca de sal, canela, espresso y leche al vapor.',
                        'featured'       => false,
                        'sort'           => 11,
                    ],
                    [
                        'name'           => 'Cookie Butter Latte',
                        'name_es'        => 'Latte de Mantequilla de Galleta',
                        'price'          => 6.00,
                        'description'    => 'Cookie butter melted with espresso and vanilla syrup, topped with crumbled cookie.',
                        'description_es' => 'Mantequilla de galleta derretida con espresso y jarabe de vainilla, coronado con galleta triturada.',
                        'featured'       => false,
                        'sort'           => 12,
                    ],
                    [
                        'name'           => 'Honey Vanilla Latte',
                        'name_es'        => 'Latte de Miel y Vainilla',
                        'price'          => 6.00,
                        'description'    => 'Honey and vanilla pulled with espresso and steamed milk, finished with a sprinkle of sea salt.',
                        'description_es' => 'Miel y vainilla con espresso y leche al vapor, con un toque de sal de mar.',
                        'featured'       => false,
                        'sort'           => 13,
                    ],
                    [
                        'name'           => 'Cappuccino',
                        'name_es'        => 'Cappuccino',
                        'price'          => 4.75,
                        'description'    => 'Equal parts espresso, steamed milk, and thick velvety foam. A timeless classic.',
                        'description_es' => 'Partes iguales de espresso, leche al vapor y espuma aterciopelada. Un clásico atemporal.',
                        'featured'       => false,
                        'sort'           => 14,
                    ],
                    [
                        'name'           => 'Americano',
                        'name_es'        => 'Americano',
                        'price'          => 3.00,
                        'description'    => 'Two shots of espresso lengthened with hot water. Clean, bold, and satisfying.',
                        'description_es' => 'Dos shots de espresso alargados con agua caliente. Limpio, intenso y satisfactorio.',
                        'featured'       => false,
                        'sort'           => 15,
                    ],
                ],
            ],
            [
                'name'           => 'Lemonade',
                'name_es'        => 'Limonada',
                'description'    => 'Hand-crafted lemonades made with real fruit and house syrups.',
                'description_es' => 'Limonadas artesanales hechas con fruta real y jarabes de la casa.',
                'sort_order'  => 2,
                'items'       => [
                    [
                        'name'           => 'Blueberry Lemonade (Small 12 oz)',
                        'name_es'        => 'Limonada de Arándano (Chica 12 oz)',
                        'price'          => 3.00,
                        'description'    => 'Fresh lemonade with house blueberry syrup. Bright, fruity, and refreshing.',
                        'description_es' => 'Limonada fresca con jarabe de arándano de la casa. Brillante, frutal y refrescante.',
                        'featured'       => false,
                        'sort'           => 1,
                    ],
                    [
                        'name'           => 'Blueberry Lemonade (Large 24 oz)',
                        'name_es'        => 'Limonada de Arándano (Grande 24 oz)',
                        'price'          => 6.00,
                        'description'    => 'Fresh lemonade with house blueberry syrup. Bright, fruity, and refreshing.',
                        'description_es' => 'Limonada fresca con jarabe de arándano de la casa. Brillante, frutal y refrescante.',
                        'featured'       => true,
                        'sort'           => 2,
                    ],
                    [
                        'name'           => 'Strawberry Lemonade (Small 12 oz)',
                        'name_es'        => 'Limonada de Fresa (Chica 12 oz)',
                        'price'          => 3.00,
                        'description'    => 'Sweet strawberry purée blended with fresh-squeezed lemonade. Summer in a cup.',
                        'description_es' => 'Puré dulce de fresa mezclado con limonada recién exprimida. Verano en una taza.',
                        'featured'       => false,
                        'sort'           => 3,
                    ],
                    [
                        'name'           => 'Strawberry Lemonade (Large 24 oz)',
                        'name_es'        => 'Limonada de Fresa (Grande 24 oz)',
                        'price'          => 6.00,
                        'description'    => 'Sweet strawberry purée blended with fresh-squeezed lemonade. Summer in a cup.',
                        'description_es' => 'Puré dulce de fresa mezclado con limonada recién exprimida. Verano en una taza.',
                        'featured'       => false,
                        'sort'           => 4,
                    ],
                ],
            ],
            [
                'name'           => 'Matcha',
                'name_es'        => 'Matcha',
                'description'    => 'Premium ceremonial-grade matcha, available hot or iced.',
                'description_es' => 'Matcha premium de grado ceremonial, disponible caliente o frío.',
                'sort_order'  => 3,
                'items'       => [
                    [
                        'name'           => 'Blueberry Matcha (Small 12 oz)',
                        'name_es'        => 'Matcha de Arándano (Chica 12 oz)',
                        'price'          => 6.50,
                        'description'    => 'Ceremonial matcha with blueberry sauce and vanilla, whisked with steamed milk.',
                        'description_es' => 'Matcha ceremonial con salsa de arándano y vainilla, batido con leche al vapor.',
                        'featured'       => true,
                        'sort'           => 1,
                    ],
                    [
                        'name'           => 'Blueberry Matcha (Large 16 oz)',
                        'name_es'        => 'Matcha de Arándano (Grande 16 oz)',
                        'price'          => 7.50,
                        'description'    => 'Ceremonial matcha with blueberry sauce and vanilla, whisked with steamed milk.',
                        'description_es' => 'Matcha ceremonial con salsa de arándano y vainilla, batido con leche al vapor.',
                        'featured'       => false,
                        'sort'           => 2,
                    ],
                    [
                        'name'           => 'Strawberry Matcha (Small 12 oz)',
                        'name_es'        => 'Matcha de Fresa (Chica 12 oz)',
                        'price'          => 6.50,
                        'description'    => 'Vibrant ceremonial matcha with house strawberry sauce and creamy steamed milk.',
                        'description_es' => 'Matcha ceremonial vibrante con salsa de fresa de la casa y leche cremosa al vapor.',
                        'featured'       => false,
                        'sort'           => 3,
                    ],
                    [
                        'name'           => 'Strawberry Matcha (Large 16 oz)',
                        'name_es'        => 'Matcha de Fresa (Grande 16 oz)',
                        'price'          => 7.50,
                        'description'    => 'Vibrant ceremonial matcha with house strawberry sauce and creamy steamed milk.',
                        'description_es' => 'Matcha ceremonial vibrante con salsa de fresa de la casa y leche cremosa al vapor.',
                        'featured'       => false,
                        'sort'           => 4,
                    ],
                ],
            ],
            [
                'name'           => 'Seasonal Drinks',
                'name_es'        => 'Bebidas de Temporada',
                'description'    => 'Rotating specials that follow what\'s fresh — available for a limited time.',
                'description_es' => 'Especiales rotativos que siguen lo más fresco — disponibles por tiempo limitado.',
                'sort_order'  => 4,
                'items'       => [
                    [
                        'name'           => 'Fresas con Crema Matcha',
                        'name_es'        => 'Matcha de Fresas con Crema',
                        'price'          => 7.00,
                        'description'    => 'Creamy strawberries-and-cream blended with ceremonial matcha. Sweet, vibrant, and indulgent.',
                        'description_es' => 'Fresas con crema mezcladas con matcha ceremonial. Dulce, vibrante e indulgente.',
                        'featured'       => true,
                        'sort'           => 1,
                    ],
                    [
                        'name'           => 'Horchata Matcha',
                        'name_es'        => 'Matcha de Horchata',
                        'price'          => 7.00,
                        'description'    => 'Traditional horchata meets ceremonial matcha — cinnamon-rice sweetness with earthy green tea.',
                        'description_es' => 'La horchata tradicional se encuentra con el matcha ceremonial — dulzura de canela y arroz con té verde terroso.',
                        'featured'       => false,
                        'sort'           => 2,
                    ],
                    [
                        'name'           => 'Peppermint Mocha Latte',
                        'name_es'        => 'Latte de Moca y Menta',
                        'price'          => 6.50,
                        'description'    => 'Mocha sauce and peppermint syrup with espresso and steamed milk, topped with crushed peppermint.',
                        'description_es' => 'Salsa de moca y jarabe de menta con espresso y leche al vapor, coronado con menta triturada.',
                        'featured'       => false,
                        'sort'           => 3,
                    ],
                    [
                        'name'           => 'Hot Chocolate',
                        'name_es'        => 'Chocolate Caliente',
                        'price'          => 5.00,
                        'description'    => 'Rich hot chocolate with peppermint syrup and steamed milk, topped with marshmallows, crushed peppermint, and mocha drizzle.',
                        'description_es' => 'Chocolate caliente con jarabe de menta y leche al vapor, coronado con malvaviscos, menta triturada y un toque de moca.',
                        'featured'       => false,
                        'sort'           => 4,
                    ],
                ],
            ],
        ];

        foreach ($menu as $catData) {
            $category = MenuCategory::create([
                'name'           => $catData['name'],
                'name_es'        => $catData['name_es'] ?? null,
                'slug'           => Str::slug($catData['name']),
                'description'    => $catData['description'],
                'description_es' => $catData['description_es'] ?? null,
                'sort_order'     => $catData['sort_order'],
                'is_active'      => true,
            ]);

            foreach ($catData['items'] as $item) {
                MenuItem::create([
                    'menu_category_id' => $category->id,
                    'name'             => $item['name'],
                    'name_es'          => $item['name_es'],
                    'slug'             => Str::slug($item['name']) . '-' . Str::random(4),
                    'description'      => $item['description'],
                    'description_es'   => $item['description_es'] ?? null,
                    'price'            => $item['price'],
                    'image_url'        => null,
                    'is_active'        => true,
                    'is_featured'      => $item['featured'],
                    'sort_order'       => $item['sort'],
                ]);
            }
        }
    }
}
